### ISSUE TITLE
Pods fail to register when using liveness command

### ISSUE THREAD

**Issue by arunvelsriram** [tczekajlo/kube-consul-register#32]
I am using `register_mode: pod` for registering the pods to consul agent running on the same node. The pod spec has a liveness probe command:

```
...
kind: Pod
...
livenessProbe:
  exec:
    command:
      - redis-cli
      - ping
  initialDelaySeconds: 5
  periodSeconds: 5
...
```

In this case, the liveness probe cannot be converted to consul health check. `kube-consul-register` is failing to register the pods because only `httpGet` and `tcpSocket` are handled here: [controller/pods/controller.go#L492](https://github.com/tczekajlo/kube-consul-register/blob/d6e28eb0f5a62d3bbf22f5806247cd9bc8790d26/controller/pods/controller.go#L492). 

This forces users to modify the `livenessProbe` to either `httpGet` or `tcpSocket`. Most of the community helm charts uses `command` as `livenessProbe`. Instead of failing to register the pods to consul we can register them without consul health check. This allows users to use the community helm charts without patching them.

Am happy to implement this fix in `kube-consul-register`. Let me know if you are okay with the idea.
